[package]
description = "Apache OpenDAL Sftp service implementation"
name = "opendal-service-sftp"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[dependencies]
fastpool = "1.0.2"
opendal-core = { path = "../../core", version = "0.55.0", default-features = false }
openssh = { version = "0.11.0" }
openssh-sftp-client = { version = "0.15.3", features = ["openssh", "tracing"] }

bytes = { workspace = true }
ctor = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["io-util", "time", "macros"] }

[dev-dependencies]
anyhow = { version = "1.0.100", features = ["std"] }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }
