[package]
name = "opendal-service-s3"
version = "0.55.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/apache/opendal"
description = "Apache OpenDAL S3 service implementation"

[package.metadata.docs.rs]
all-features = true

[dependencies]
opendal-core = { path = "../../core", version = "0.55.0", default-features = false }
base64 = "0.22"
bytes = "1.6"
crc32c = "0.6.6"
ctor = "0.6"
http = "1.1"
log = "0.4"
md-5 = "0.10"
quick-xml = { version = "0.38", features = ["serialize", "overlapped-lists"] }
reqsign-aws-v4 = { version = "2.0.1", default-features = false }
reqsign-core = { version = "2.0.1", default-features = false }
reqsign-file-read-tokio = { version = "2.0.1", default-features = false }
reqsign-http-send-reqwest = { version = "2.0.1", default-features = false }
reqwest = { version = "0.12.24", features = ["stream"], default-features = false }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1"
tracing-subscriber = "0.3"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread", "io-util"] }
serde_json = "1"
