# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
categories = ["filesystem"]
description = "OpenDAL Gateway"
keywords = ["storage", "data", "s3", "fs", "azblob"]
name = "oay"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["frontends-webdav", "frontends-s3"]

frontends-s3 = []
frontends-webdav = [
  "dep:dav-server",
  "dep:dav-server-opendalfs",
  "dep:bytes",
  "dep:futures-util",
]

[dependencies]
anyhow = "1"
axum = "0.6"
bytes = { version = "1.5.0", optional = true }
chrono = "0.4.31"
clap = { version = "4", features = ["cargo", "string"] }
dav-server = { version = "0.5.8", optional = true }
dav-server-opendalfs = { path = "../../integrations/dav-server", optional = true }
dirs = "5.0.1"
futures = "0.3"
futures-util = { version = "0.3.29", optional = true }
opendal.workspace = true
quick-xml = { version = "0.30", features = ["serialize", "overlapped-lists"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.34", features = [
  "fs",
  "macros",
  "rt-multi-thread",
  "io-std",
] }
toml = "0.8.8"
tower = "0.4"
tower-http = { version = "0.4", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5.0"
uuid = { version = "1", features = ["v4", "fast-rng"] }
