[package]
# name for this package
name = "setup"
# edition is the rust edition that used to complie this package.
# We will not discuss about this a lot, use `2021` is a good choice.
#
# For more information: <https://doc.rust-lang.org/edition-guide/editions/>
edition = "2021"
# version is the semver for this pacakge.
# We will not publish this package publicly, so the version is leave AS-IS.
version = "0.1.0"

# In this example, we are depending on two crates (packages): `futures` and `opendal`
[dependencies]
futures = "0.3"
# The `0.37` is the semver version of opendal.
#
# We use `0.37` to indicate all versions that `>=0.37.0 && <0.38.0`.
opendal = "0.37"
