# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Fuzz Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "core/src/**"
      - "core/fuzz/**"
      - "!core/src/docs/**"
      - "!core/src/services/**"
      - "core/src/services/fs/**"
      - "core/src/services/memory/**"
      - "core/src/services/s3/**"
      - ".github/workflows/fuzz_test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  fuzz-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
      - name: Install libfuzz
        shell: bash
        run: sudo apt-get install -y libfuzzer-14-dev

      - name: Install cargo fuzz
        shell: bash
        run: rustup install nightly && cargo +nightly install cargo-fuzz
      - name: Build Fuzz Targets
        shell: bash
        working-directory: core/fuzz
        run: cargo +nightly fuzz build
        env:
          CUSTOM_LIBFUZZER_PATH: /usr/lib/llvm-14/lib/libFuzzer.a

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fuzz_targets
          path: |
            ./target/x86_64-unknown-linux-gnu/release/fuzz_reader
            ./target/x86_64-unknown-linux-gnu/release/fuzz_reader_with_buffer
            ./target/x86_64-unknown-linux-gnu/release/fuzz_writer

  fuzz-test-s3:
    runs-on: ubuntu-latest
    needs: fuzz-build
    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "minioadmin"
          MINIO_SECRET_KEY: "minioadmin"
    strategy:
      fail-fast: true
      matrix:
        fuzz-targets: [fuzz_reader, fuzz_reader_with_buffer, fuzz_writer]
    steps:
      - name: Install libfuzzer
        run: sudo apt-get install -y libfuzzer-14-dev
      - name: Setup Test Bucket
        env:
          AWS_ACCESS_KEY_ID: "minioadmin"
          AWS_SECRET_ACCESS_KEY: "minioadmin"
          AWS_EC2_METADATA_DISABLED: "true"
        run: aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://test
      - name: Download Fuzz Targets
        uses: actions/download-artifact@v3
        with:
          name: fuzz_targets
          path: ./target
      - name: Grant Execute Permissions
        shell: bash
        run: chmod +x ./target/${{ matrix.fuzz-targets }}
      - name: Run Fuzz Test
        shell: bash
        run: ./target/${{ matrix.fuzz-targets }} -max_total_time=120
        env:
          OPENDAL_S3_TEST: on
          OPENDAL_S3_BUCKET: test
          OPENDAL_S3_ENDPOINT: "http://127.0.0.1:9000"
          OPENDAL_S3_ACCESS_KEY_ID: minioadmin
          OPENDAL_S3_SECRET_ACCESS_KEY: minioadmin
          OPENDAL_S3_REGION: us-east-1

  fuzz-test-fs:
    runs-on: ubuntu-latest
    needs: fuzz-build
    strategy:
      fail-fast: true
      matrix:
        fuzz-targets: [fuzz_reader, fuzz_reader_with_buffer, fuzz_writer]
    steps:
      - name: Install libfuzzer
        run: sudo apt-get install -y libfuzzer-14-dev
      - name: Download Fuzz Targets
        uses: actions/download-artifact@v3
        with:
          name: fuzz_targets
          path: ./target
      - name: Grant Execute Permissions
        shell: bash
        run: chmod +x ./target/${{ matrix.fuzz-targets }}
      - name: Run Fuzz Test
        shell: bash
        run: ./target/${{ matrix.fuzz-targets }} -max_total_time=120
        env:
          OPENDAL_FS_TEST: on
          OPENDAL_FS_ROOT: ${{ runner.temp }}/

  fuzz-test-memory:
    runs-on: ubuntu-latest
    needs: fuzz-build
    strategy:
      fail-fast: true
      matrix:
        fuzz-targets: [fuzz_reader, fuzz_reader_with_buffer, fuzz_writer]
    steps:
      - name: Install libfuzzer
        run: sudo apt-get install -y libfuzzer-14-dev
      - name: Download Fuzz Targets
        uses: actions/download-artifact@v3
        with:
          name: fuzz_targets
          path: ./target
      - name: Grant Execute Permissions
        shell: bash
        run: chmod +x ./target/${{ matrix.fuzz-targets }}
      - name: Run Fuzz Test
        shell: bash
        run: ./target/${{ matrix.fuzz-targets }} -max_total_time=120
        env:
          OPENDAL_MEMORY_TEST: on


  fuzz-test-azure:
    runs-on: ubuntu-latest
    needs: fuzz-build
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
    strategy:
      fail-fast: true
      matrix:
        fuzz-targets: [fuzz_reader, fuzz_reader_with_buffer, fuzz_writer]
    steps:
      - name: Install libfuzzer
        run: sudo apt-get install -y libfuzzer-14-dev
      - name: Setup test bucket
        shell: bash
        run: |
          az storage container create \
              --name test \
              --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
      - name: Download Fuzz Targets
        uses: actions/download-artifact@v3
        with:
          name: fuzz_targets
          path: ./target
      - name: Grant Execute Permissions
        shell: bash
        run: chmod +x ./target/${{ matrix.fuzz-targets }}
      - name: Run Fuzz Test
        shell: bash
        run: ./target/${{ matrix.fuzz-targets }} -max_total_time=120
        env:
          OPENDAL_AZBLOB_TEST: on
          OPENDAL_AZBLOB_CONTAINER: test
          OPENDAL_AZBLOB_ENDPOINT: "http://127.0.0.1:10000/devstoreaccount1"
          OPENDAL_AZBLOB_ACCOUNT_NAME: devstoreaccount1
          OPENDAL_AZBLOB_ACCOUNT_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="

