name: Service Test IPFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  # Run this test every hour to keep our testdata warm in ipfs network.
  schedule:
    - cron: "0 * * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ipfs-daemon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up IPFS ${{ matrix.ipfs }}
        uses: ibnesayeed/setup-ipfs@cacf727ab8eae418dc4a2534c2c2c19343021c7c
        id: ipfs_setup
        with:
          # ipfs v0.15 seems can't pass our tests, need investigate.
          ipfs_version: "v0.14.0"
      - name: Start IPFS Daemon
        run: |
          ipfs config --json Gateway.NoFetch true
          ipfs daemon &
      - name: IPFS add speed up tests
        run: ipfs add -r ./testdata

      - name: Test
        shell: bash
        run: cargo test ipfs --features compress,layers-retry,services-ipfs -- --nocapture
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_IPFS_TEST: on
          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
          OPENDAL_IPFS_ENDPOINT: "http://127.0.0.1:8080"

#  # ipfs.io can't pass our test by now, we should address them in the future.
#  ipfs-io:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test
#        shell: bash
#        run: cargo test ipfs --features compress,layers-retry,services-ipfs -- --nocapture
#        env:
#          RUST_BACKTRACE: full
#          RUST_LOG: debug
#          OPENDAL_IPFS_TEST: on
#          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
#          OPENDAL_IPFS_ENDPOINT: "https://ipfs.io"
