name: Service Test IPFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!src/docs/**"
      - "!src/services/**"
      - "src/services/ipfs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ipfs-daemon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up IPFS ${{ matrix.ipfs }}
        uses: ibnesayeed/setup-ipfs@aff2e4ae38368a44ac36ecc244f8c693d2e5b263
        id: ipfs_setup
        with:
          ipfs_version: "v0.16.0"
          run_daemon: true
      - name: IPFS Add testdata
        run: |
          ipfs add -r ./tests/data --to-files /opendal-testdata
          ipfs files ls /opendal-testdata -l
      - uses: Swatinem/rust-cache@v2
      - name: Test
        shell: bash
        run: cargo test ipfs --features services-ipfs -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_IPFS_TEST: on
          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
          OPENDAL_IPFS_ENDPOINT: "http://127.0.0.1:8080"
#  # ipfs.io can't pass our test by now, we should address them in the future.
#  ipfs-io:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test
#        shell: bash
#        run: cargo test ipfs --features compress,services-ipfs -- --show-output
#        env:
#          RUST_BACKTRACE: full
#          RUST_LOG: debug
#          OPENDAL_IPFS_TEST: on
#          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
#          OPENDAL_IPFS_ENDPOINT: "https://ipfs.io"
