# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Service Test IPFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "core/src/**"
      - "core/tests/**"
      - "!core/src/docs/**"
      - "!core/src/services/**"
      - "core/src/services/ipfs/**"
      - ".github/workflows/service_test_ipfs.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ipfs-daemon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up IPFS ${{ matrix.ipfs }}
        uses: ibnesayeed/setup-ipfs@c779340c110024feeb46579fef211c89332caf85
        id: ipfs_setup
        with:
          ipfs_version: "v0.16.0"
          run_daemon: true
      - name: IPFS Add testdata
        run: |
          ipfs add -r ./tests/data --to-files /opendal-testdata
          ipfs files ls /opendal-testdata -l
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          need-nextest: true
      - name: Test
        shell: bash
        working-directory: core
        run: cargo nextest run ipfs --features services-ipfs
        env:
          OPENDAL_IPFS_TEST: on
          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
          OPENDAL_IPFS_ENDPOINT: "http://127.0.0.1:8080"
          OPENDAL_DISABLE_RANDOM_ROOT: true

#  # ipfs.io can't pass our test by now, we should address them in the future.
#  ipfs-io:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test
#        shell: bash
#        run: cargo test ipfs --features services-ipfs -- --show-output
#        env:
#          RUST_BACKTRACE: full
#          RUST_LOG: debug
#          OPENDAL_IPFS_TEST: on
#          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
#          OPENDAL_IPFS_ENDPOINT: "https://ipfs.io"
