name: Service Test Memcached

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!src/docs/**"
      - "!src/services/**"
      - "src/services/memcached/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  memcached:
    runs-on: ubuntu-latest

    # Setup memcached server
    services:
      memcached:
        image: bitnami/memcached
        env:
          # memcache's max item size is 1MiB, But opendal's behavior tests
          # will produce larger file.
          #
          # Specify the setting here to make our test happy.
          MEMCACHED_MAX_ITEM_SIZE: 16777216
        ports:
          - 11211:11211

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Test
        shell: bash
        run: cargo test memcached --features compress,services-memcached -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_MEMCACHED_TEST: on
          OPENDAL_MEMCACHED_ENDPOINT: tcp://127.0.0.1:11211
          OPENDAL_MEMCACHED_ROOT: /
