name: Service Test WebDAV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  nginx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nginx full for dav_ext modules
        run: apt install nginx-full

      - name: Start nginx
        shell: bash
        run: |
          mkdir -p /tmp/static
          nginx -c `pwd`/src/services/webdav/fixtures/nginx.conf

      - name: Test
        shell: bash
        run: cargo test webdav --features compress -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_WEBDAV_TEST: on
          OPENDAL_WEBDAV_ENDPOINT: http://127.0.0.1:8080

  nginx_with_password:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start nginx
        shell: bash
        run: |
          mkdir -p /tmp/static
          cp `pwd`/src/services/webdav/fixtures/htpasswd /tmp/htpasswd
          nginx -c `pwd`/src/services/webdav/fixtures/nginx-with-basic-auth.conf

      - name: Test empty password
        shell: bash
        run: cargo test webdav --features compress -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_WEBDAV_TEST: on
          OPENDAL_WEBDAV_ENDPOINT: http://127.0.0.1:8080
          OPENDAL_WEBDAV_USERNAME: foo

      - name: Test with password
        shell: bash
        run: cargo test webdav --features compress -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_WEBDAV_TEST: on
          OPENDAL_WEBDAV_ENDPOINT: http://127.0.0.1:8080
          OPENDAL_WEBDAV_USERNAME: bar
          OPENDAL_WEBDAV_PASSWORD: bar
