name: Service Test Ftp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  vsftpd:
    runs-on: ubuntu-latest

    services:
      ftp:
        image: fauria/vsftpd
        ports:
          - 2121:21
          - 21000-22000:21000-22000
        env:
          FTP_USER: admin
          FTP_PASS: admin
          PASV_ADDRESS: 127.0.0.1
          PASV_MIN_PORT: 21000
          PASV_MAX_PORT: 22000
        volumes:
          - vsftpd-data:/home/vsftpd

    steps:
      - uses: actions/checkout@v3
      - name: Test
        shell: bash
        run: cargo test ftp --features compress,layers-retry,services-ftp -- --nocapture
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_FTP_TEST: on
          OPENDAL_FTP_ENDPOINT: 127.0.0.1:2121
          OPENDAL_FTP_ROOT: /
          OPENDAL_FTP_USER: admin
          OPENDAL_FTP_PASSWORD: admin
